server:
  port: 8768

spring:
  application:
    name: user-oauth2-service
#  security:
#    user:
#      name: admin
#      password: enjoy1
  redis:
    host: 127.0.0.1
    port: 6379
    password:

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true