server:
  port: 8763

spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: admin
      password: enjoy

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      defaultZone: http://127.0.0.1:8861/eureka/,http://127.0.0.1:8761/eureka/

feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.test.user.api.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      test:
        user:
          dao: info