server:
  port: 8766

spring:
  application:
    name: security-service
#  security:
#    user:
#      name: admin
#      password: enjoy1

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true