server:
  port: 8862

spring:
  application:
    name: client-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8861/eureka/,http://127.0.0.1:8761/eureka/

feign:
  hystrix:
    enabled: true