server:
  port: 8761

spring:
  application:
    name: eureka-service


eureka:
  instance:
    hostname: eureka
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8861/eureka/,http://127.0.0.1:8761/eureka/
